name: Docker Build & Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:   
      - run: echo ${{secrets.DOCKER_USER}} 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: docker login --username=${{ secrets.DOCKER_USER }} --password=${{ secrets.DOCKER_PASSWORD }} 

      - run: ./build.sh
