name: Docker Build & Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} 

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - run: |
          docker build . && docker build -t 1key/nchan . 
          docker push 1key/nchan
